openapi: 3.0.3
info:
  title: Invoice Management API
  description: API for managing invoices, users, and payments.
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /health:
    get:
      summary: Health check
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties: { status: { type: string, example: "ok" } }

  /users:
    get:
      summary: List users
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items: { $ref: "#/components/schemas/UserDTO" }

components:
  schemas:
    UserDTO:
      type: object
      required: [id, email, firstName, lastName, role, phone]
      properties:
        id:        { type: integer, format: int64 }
        email:     { type: string, format: email }
        phone:     { type: string, example: "+390611111111" }
        firstName: { type: string }
        lastName:  { type: string }
        role:      { type: string, enum: [ADMIN, USER], example: "ADMIN" }


